// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_settings.sql

package sqlc

import (
	"context"
)

const getAppSetting = `-- name: GetAppSetting :one
SELECT key, value, updated_at
FROM app_settings
WHERE key = ?
`

func (q *Queries) GetAppSetting(ctx context.Context, key string) (AppSetting, error) {
	row := q.db.QueryRowContext(ctx, getAppSetting, key)
	var i AppSetting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const upsertAppSetting = `-- name: UpsertAppSetting :one
INSERT INTO app_settings (key, value, updated_at)
VALUES (?, ?, CURRENT_TIMESTAMP)
ON CONFLICT (key) DO UPDATE
SET value = excluded.value,
    updated_at = CURRENT_TIMESTAMP
RETURNING key, value, updated_at
`

type UpsertAppSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertAppSetting(ctx context.Context, arg UpsertAppSettingParams) (AppSetting, error) {
	row := q.db.QueryRowContext(ctx, upsertAppSetting, arg.Key, arg.Value)
	var i AppSetting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}
