services:
  qdrant:
    image: memoh.cn/qdrant/qdrant:latest
  migrate:
    image: memoh.cn/memohai/server:latest
  server:
    image: memoh.cn/memohai/server:latest
  web:
    image: memoh.cn/memohai/web:latest
  sparse:
    image: memoh.cn/memohai/sparse:latest
